### PR TITLE
Fix whitespace around "github.com"

### PR DESCRIPTION
**Pull request by smashwilson**
On `/projects/new` with no `ENTERPRISE_HOSTS` specified, the template was
emitting whitespace around "github.com" that looked weird.

### CODE REVIEW

**Comment by parkr** [comment]
This logic should probably be in a helper. Thoughts?

**Comment by smashwilson** [comment]
Hmm, I could extract it, yeah. I'd have to make the `FormHelper` an argument, though (or add arguments to manually reproduce what `f.select` gives for free).

**Comment by parkr** [comment]
Or you could pass `f`. Totally up to you though, just a thought.

**Comment by cobyism** [comment]
@parkr Usually, I’d agree with you, but I’m not really that worried about logic in the views for this app getting out of control. It’s pretty small and I don’t really see it becoming a huge problem. #famouslastwords

**Comment by cobyism** [comment]
There was a merge conflict here after the latest change from #25, so I just redid this in a way that’s slightly more concise—even though it’s slightly more repetitive, I think it makes the intention clearer.

**Pull request merged**
